name: sd-scripts
channels:
  - defaults
dependencies:
  - python=3.10
  - pip=23.3.1
  - pip:
     - --extra-index-url https://download.pytorch.org/whl/cu118
     - torch==2.0.1+cu118
     - torchvision==0.15.2+cu118 
     - xformers==0.0.20
     - -r requirements.txt
     - -e ../pyviewer

# conda env create --force -f environment.yml
